---
title: "item_prep"
author: "Gabriel Strain"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading in packages

```{r libraries}
library(tidyverse)
library(png)
library(forcats)
library(ggalt)
library(scales)
library(grid)
library(tidyr)
library(ggdist)
library(gtools)
```


```{r bar-plots}
plot_series <- (1:45)

bar_func <- function(ceiling, gran) {
  
  set.seed(counter)
  x <- (1:ceiling)
  y <- runif(ceiling, 10, 100)
  data <- data.frame(x,y)
  
  min_x <- data %>%
    slice_min(y)
  
  correct_low <- min_x$x
  
  max_x <- data %>%
    slice_max(y)
  
  correct_high <- max_x$x
  
  bar_plot <- ggplot(aes(x, y), data = data) +
    geom_bar(stat = "identity") +
    labs(x = "",
         y = "") +
    theme(axis.text.x = element_blank()) +
    theme_ggdist() +
    ylim(0,100) +
    xlim(0, ceiling)
    
  ggsave(bar_plot, filename=paste0(counter, "_bar_", gran, "_l_", correct_low, "_h_", correct_high, ".png"), 
       device = "png",
       bg = "white",
       path = "all_plots",
       units = "px",
       width = 1500,
       height = 1000,  
  )
  
}

```

```{r line-plots}
line_func <- function(ceiling, gran) {
  
  set.seed(counter)
  x <- (1:ceiling)
  y <- runif(ceiling, 10, 100)
  data <- data.frame(x,y)
  
  min_x <- data %>%
    slice_min(y)
  
  correct_low <- min_x$x
  
  max_x <- data %>%
    slice_max(y)
  
  correct_high <- max_x$x
  
  
  plot <- ggplot(aes(x, y, group = 1), data = data) +
    geom_line(size = 1) +
    labs(x = "",
         y = "") +
    theme(axis.text.x = element_blank()) +
    theme_ggdist() +
    ylim(0,100) +
    xlim(0, ceiling)
    
  ggsave(plot, filename=paste0(counter, "_line_", gran, "_l_", correct_low, "_h_", correct_high, ".png"), 
       device = "png",
       bg = "white",
       path = "all_plots",
       units = "px",
       width = 1500,
       height = 1000,  
  )
  
}

```
 
```{r plot_generator}
counter = 1

for (value in plot_series) {
  bar_func(40, "HG")
  if (counter > 0) {
    counter = counter + 1
  }
}

counter = 1

for (value in plot_series) {
  bar_func(10, "LG")
  if (counter > 0) {
    counter = counter + 1
  }
}

counter = 1

for (value in plot_series) {
  line_func(40, "HG")
  if (counter > 0) {
    counter = counter + 1
  }
}

counter = 1

for (value in plot_series) {
  line_func(10, "LG")
  if (counter > 0) {
    counter = counter + 1
  }
}
```

# Assembling .csv

```{r}
images <- mixedsort(list.files(path = "all_plots"))

plot_labels <- rep(c("all_plots/"), each = 180)

plots_with_labels <- paste(plot_labels, images, sep = "")

unique_item_no <- c(1:180)

instructions <- rep(c("Approximately how far along the x axis is the lowest y value?",
                      "Approximately how far along the x axis is the highest y value"), 90)

data_with_plots <- cbind(unique_item_no, plots_with_labels, images, instructions)
```

# Creating masks

```{r}
mask_gen_function <- function() {

x <- LETTERS[1:20]
y <- paste0("var", seq(1,20))
data <- expand.grid(X=x, Y=y)
data$Z <- round(runif(400, 0, 1))

mask <- ggplot(data, aes(X, Y, fill= Z)) + 
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black") +
  theme_void() +
  theme(legend.position = "None")

ggsave(mask,filename=paste("mask", counter,".png",sep=""),
       device = "png",
       bg = "white",
       path = "masks",
       units = "px",
       width = 1500,
       height = 1000,)
}

counter = 1
for (i in 1:186) {
  mask_gen_function()
  if (counter > 0) {
    counter = counter + 1
  }
}

masks <- mixedsort(list.files(path = "masks"))

mask_labels <- rep(c("masks/"), each = 186)

masks_with_labels <- paste(mask_labels, masks, sep = "")
```

# Attaching height and width values to each plot, instructions column, and masks vector

```{r}
size_w <- rep(c(1), times = 180)

size_h <- rep(c(0.75), times = 180)

colour <- rep(c("black"), times = 180)

data_with_sizes <- cbind(data_with_plots, size_h, size_w, colour)
```

# Creating attention_check DF.

```{r}

plots_with_labels <- head(plots_with_labels)

images <- head(images)

unique_item_no <- c(181:186)

size_h <- rep(c(1), times = 6)

size_w <- rep(c(0.75), times = 6)

colour <- rep(c("red"), times = 6)

instructions <- rep(c("Please IGNORE the plot displayed and type 100 in the box.",
                      "Please IGNORE the plot displayed and and type 0 in the box"),
                    times = c(3, 3))

attention_checks <- cbind(unique_item_no, plots_with_labels, images,
                          size_h, size_w, instructions, colour)
```

# Creating the final DF by rbinding attention_checks with data_with_sizes

```{r}
trusty_viz_data <- rbind(data_with_sizes, attention_checks) %>%
  cbind(masks_with_labels)

write.csv(trusty_viz_data, "trust_viz_data.csv", row.names = FALSE)
```

# Practice trials

```{r}
practice_data <- head(trusty_viz_data)


write.csv(practice_data, "practice_plots.csv", row.names = FALSE)
```

 
 
 
 
 
 
 
 
 
 
 
